default: true

MD004:
  style: "sublist"

MD013:
  code_blocks: false
  tables: false

MD024:
  siblings_only: true

MD028: false

MD029:
  style: "ordered"

MD031:
  list_items: false

MD032: false

MD041: false

MD045: false
