[tool.black]
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
)/
'''
line-length = 99
skip-string-normalization = true # don't force double quotes

[tool.isort]
profile = "hug"
line_length = 99

[tool.flake8]
ignore = "E203, W503, W605"
exclude = ".git, .mypy_cache, .pytest_cache, build, dist"
max-line-length = 99
max-complexity = 20

[tool.mypy]
disallow_any_unimported = false 
ignore_missing_imports = true

check_untyped_defs = true
# disallow_incomplete_defs = true
# disallow_untyped_calls = true
warn_unused_configs = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
