[tool.black]
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
)/
'''
line-length = 99
skip-string-normalization = true # don't force double quotes

[tool.isort]
profile = "hug"
line_length = 99

